var params;

function setup(){

//Creating the button links to the games
//TODO: make these cool and autogenerated from Games folder (which stands in for out file server)
ballGameButton = createButton("ballGame!");
ballGameButton.position(windowWidth/3, 200);
// () => {} notation to make a function on the fly
ballGameButton.mousePressed(() => {
  selectGame("ballGame");
});
testGameButton = createButton("testGame!");
testGameButton.position(windowWidth*2/3, 200);
testGameButton.mousePressed(() => {
  selectGame("testGame");
});

//Initializing URLSearchParams object, which we use to write/read all the game title parameters in the urls
params = new URLSearchParams(window.location.search);
}

function selectGame(game){
  //When a game is selected, send player to play.html with gamename parameter in the url (?game="gameName")
  params.append("game", game);
  window.location.href = "pages/play.html?"+params;
}
